export interface ClientRequest {
  id: number;
  clientName: string;
  caseTitle: string;
  submittedDate: string;
  status?: string;
  nextHearingDate?: string;
}

export interface Service {
  id: string;
  title: string;
  description: string;
  price: number;
  time: string;
  rating: number;
  image: string;
  serviceTag: string;
}

export enum Role {
  LAWYER = "LAWYER",
  CLIENT = "CLIENT",
}

export interface UserType {
  id: string;
  role?: Role;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone_number?: string;
  address?: string;
  addhar_number?: string;
  profile?: string;
  createdAt?: string | Date;
  updatedAt?: string | Date;
  Lawyer?: {
    profile_description?: string;
    yoe?: number;
    specialization?: string;
    license_number?: string;
    bar_association_membership?: string;
    consultationFee?: number;
    website?: string;
    id?: string;
  };
}

export interface AppointmentsType {
  id?: string;
  client_id?: string;
  lawyer_id?: string;
  description: string;
  date: Date;
  status?: APPOINTMENT_STATUS;
  createdAt?: Date;
  updatedAt?: Date;
  role?: Role;
  client?: {
    firstName: string;
    lastName: string;
    email: string;
    phone_number: string;
  };
  lawyer?: {
    user: {
      firstName: string;
      lastName: string;
      email: string;
      phone_number: string;
    };
  };
}

export enum APPOINTMENT_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  COMPLETED = "COMPLETED",
  CANCELED = "CANCELED",
}

export interface ServiceType {
  id?: string; // Optional, as it will be generated by the database
  title: string;
  description: string;
  category: string;
  price: number;
  createdAt?: string; // Optional, as it will be generated by the database
  updatedAt?: string; // Optional, as it will be updated automatically
  userId?: string;
}

export interface LawyerDetailsType {
  id: string;
  profile_description: string;
  website: string;
  yoe: number; // Years of Experience
  Ratings: Rating[]; // Array of ratings
  specialization: string;
  consultationFee: number;
  createdAt: Date;
  updatedAt: Date;
  Appointments?: AppointmentsType[]; // Appointments is optional and conditionally included
  services: ServiceType[];
  user: {
    firstName: string;
    lastName: string;
    email: string;
    address: string;
  };
}

export interface Rating {
  rating: number;
  client_id: string;
  lawyer_id: string;
  description: string;
  id: string;
}


// export interface CaseType {
//   id?: string;
//   title: string;
//   description?: string;
//   status: CASE_STATUS;
//   createdAt?: string;
//   updateAt?: string;
//   client?: {
//     client_id?: string;
//     firstName?: string;
//     lastName?: string;
//     email?: string;
//     phone_number?: string;
//   };
//   lawyer?: {
//     lawyer_id?: string;
//     firstName?: string;
//     lastName?: string;
//     email?: string;
//     phone_number?: string;
//   };
//   hearings?: HearingType[];
//   timeline?: TimelineType[];
// }

export interface CaseType {
  id: string;
  title: string;
  description: string;
  status: string;
  win: boolean;
  client: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    phone_number: string;
    address: string;
  };
  Hearings: {
    id?: string;
    createdAt: Date;
    updatedAt: Date;
    status: string;
  }[];
  Timeline: {
    id: string;
    title: string;
    description: string;
    status: string;
    createdAt: Date;
    updatedAt: Date;
  }[];
  CaseLawyer: {
    lawyer: {
      id: string;
      user: {
        firstName: string;
        lastName: string;
        email: string;
        phone_number: string;
        address: string;
      };
    };
  }[];
};

export enum CASE_STATUS {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ONGOING = 'ONGOING'
}

export enum TimelineStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ONGOING = 'ONGOING'
}


export interface TimelineType {
  id: string;
  title: string;
  description: string;
  status: TIME_LINE_STATUS;
  createdAt: Date;
}

export interface HearingType {
  id?: string;
  client_id: string;
  date: Date;
  status: HEARING_STATUS;
  lawyer_id: string;
}

export enum HEARING_STATUS {
  UPCOMING = 'UPCOMING',
  CLOSED = 'CLOSED',
}

export enum TIME_LINE_STATUS {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ONGOING = 'ONGOING',
}